export const countries: {
    [key: string]: { ar: string; code: string; en: string };
  } = {
    AD: { ar: "أندورا", code: "AD", en: "Andorra" },
    AE: {
      ar: "الإمارات العربية المتحدة",
      code: "AE",
      en: "United Arab Emirates",
    },
    AF: { ar: "أفغانستان", code: "AF", en: "Afghanistan" },
    AG: { ar: "أنتيغوا وبربودا", code: "AG", en: "Antigua and Barbuda" },
    AI: { ar: "أنغويلا", code: "AI", en: "Anguilla" },
    AL: { ar: "ألبانيا", code: "AL", en: "Albania" },
    AM: { ar: "أرمينيا", code: "AM", en: "Armenia" },
    AN: { ar: "جزر الأنتيل الهولندية", code: "AN", en: "Netherlands Antilles" },
    AO: { ar: "أنغولا", code: "AO", en: "Angola" },
    AQ: { ar: "أنتاركتيكا", code: "AQ", en: "Antarctica" },
    AR: { ar: "الأرجنتين", code: "AR", en: "Argentina" },
    AS: { ar: "ساموا الأمريكية", code: "AS", en: "American Samoa" },
    AT: { ar: "النمسا", code: "AT", en: "Austria" },
    AU: { ar: "أستراليا", code: "AU", en: "Australia" },
    AW: { ar: "آروبا", code: "AW", en: "Aruba" },
    AZ: { ar: "أذربيجان", code: "AZ", en: "Azerbaijan" },
    BA: { ar: "البوسنة والهرسك", code: "BA", en: "Bosnia and Herzegovina" },
    BB: { ar: "بربادوس", code: "BB", en: "Barbados" },
    BD: { ar: "بنجلاديش", code: "BD", en: "Bangladesh" },
    BE: { ar: "بلجيكا", code: "BE", en: "Belgium" },
    BF: { ar: "بوركينا فاسو", code: "BF", en: "Burkina Faso" },
    BG: { ar: "بلغاريا", code: "BG", en: "Bulgaria" },
    BH: { ar: "البحرين", code: "BH", en: "Bahrain" },
    BI: { ar: "بوروندي", code: "BI", en: "Burundi" },
    BJ: { ar: "بنين", code: "BJ", en: "Benin" },
    BM: { ar: "برمودا", code: "BM", en: "Bermuda" },
    BN: { ar: "بروناي", code: "BN", en: "Brunei Darussalam" },
    BO: { ar: "بوليفيا", code: "BO", en: "Bolivia" },
    BR: { ar: "البرازيل", code: "BR", en: "Brazil" },
    BS: { ar: "الباهاما", code: "BS", en: "Bahamas" },
    BT: { ar: "بوتان", code: "BT", en: "Bhutan" },
    BU: { ar: "Burma", code: "BU", en: "Burma" },
    BV: { ar: "جزيرة بوفيه", code: "BV", en: "Bouvet Island" },
    BW: { ar: "بتسوانا", code: "BW", en: "Botswana" },
    BY: { ar: "روسيا البيضاء", code: "BY", en: "Belarus" },
    BZ: { ar: "بليز", code: "BZ", en: "Belize" },
    CA: { ar: "كندا", code: "CA", en: "Canada" },
    CC: { ar: "جزر كوكوس", code: "CC", en: "Cocos  Islands" },
    CD: { ar: "الكونغو - كينشاسا", code: "CD", en: "Congo" },
    CF: {
      ar: "جمهورية أفريقيا الوسطى",
      code: "CF",
      en: "Central African Republic",
    },
    CG: { ar: "الكونغو - برازافيل", code: "CG", en: "Congo" },
    CH: { ar: "سويسرا", code: "CH", en: "Switzerland" },
    CI: { ar: "ساحل العاج", code: "CI", en: "Cote D'Ivoire" },
    CK: { ar: "جزر كوك", code: "CK", en: "Cook Islands" },
    CL: { ar: "شيلي", code: "CL", en: "Chile" },
    CM: { ar: "الكاميرون", code: "CM", en: "Cameroon" },
    CN: { ar: "الصين", code: "CN", en: "China" },
    CO: { ar: "كولومبيا", code: "CO", en: "Colombia" },
    CR: { ar: "كوستاريكا", code: "CR", en: "Costa Rica" },
    CS: { ar: "Serbia and Montenegro", code: "CS", en: "Serbia and Montenegro" },
    CU: { ar: "كوبا", code: "CU", en: "Cuba" },
    CV: { ar: "الرأس الأخضر", code: "CV", en: "Cape Verde" },
    CX: { ar: "جزيرة الكريسماس", code: "CX", en: "Christmas Island" },
    CY: { ar: "قبرص", code: "CY", en: "Cyprus" },
    CZ: { ar: "جمهورية التشيك", code: "CZ", en: "Czech Republic" },
    DE: { ar: "ألمانيا", code: "DE", en: "Germany" },
    DJ: { ar: "جيبوتي", code: "DJ", en: "Djibouti" },
    DK: { ar: "الدانمرك", code: "DK", en: "Denmark" },
    DM: { ar: "دومينيكا", code: "DM", en: "Dominica" },
    DO: { ar: "جمهورية الدومينيك", code: "DO", en: "Dominican Republic" },
    DZ: { ar: "الجزائر", code: "DZ", en: "Algeria" },
    EC: { ar: "الإكوادور", code: "EC", en: "Ecuador" },
    EE: { ar: "أستونيا", code: "EE", en: "Estonia" },
    EG: { ar: "مصر", code: "EG", en: "Egypt" },
    EH: { ar: "الصحراء الغربية", code: "EH", en: "Western Sahara" },
    ER: { ar: "أريتريا", code: "ER", en: "Eritrea" },
    ES: { ar: "إسبانيا", code: "ES", en: "Spain" },
    ET: { ar: "إثيوبيا", code: "ET", en: "Ethiopia" },
    FI: { ar: "فنلندا", code: "FI", en: "Finland" },
    FJ: { ar: "فيجي", code: "FJ", en: "Fiji" },
    FK: { ar: "جزر فوكلاند", code: "FK", en: "Falkland Islands" },
    FM: { ar: "ميكرونيزيا", code: "FM", en: "Micronesia" },
    FO: { ar: "جزر فارو", code: "FO", en: "Faeroe Islands" },
    FR: { ar: "فرنسا", code: "FR", en: "France" },
    GA: { ar: "الجابون", code: "GA", en: "Gabon" },
    GB: { ar: "المملكة المتحدة", code: "GB", en: "United Kingdom" },
    GD: { ar: "غرينادا", code: "GD", en: "Grenada" },
    GE: { ar: "جورجيا", code: "GE", en: "Georgia" },
    GF: { ar: "غويانا الفرنسية", code: "GF", en: "French Guiana" },
    GH: { ar: "غانا", code: "GH", en: "Ghana" },
    GI: { ar: "جبل طارق", code: "GI", en: "Gibraltar" },
    GL: { ar: "غرينلاند", code: "GL", en: "Greenland" },
    GM: { ar: "غامبيا", code: "GM", en: "Gambia" },
    GN: { ar: "غينيا", code: "GN", en: "Guinea" },
    GP: { ar: "جوادلوب", code: "GP", en: "Guadaloupe" },
    GQ: { ar: "غينيا الاستوائية", code: "GQ", en: "Equatorial Guinea" },
    GR: { ar: "اليونان", code: "GR", en: "Greece" },
    GS: {
      ar: "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
      code: "GS",
      en: "South Georgia and the South Sandwich Islands",
    },
    GT: { ar: "غواتيمالا", code: "GT", en: "Guatemala" },
    GU: { ar: "غوام", code: "GU", en: "Guam" },
    GW: { ar: "غينيا بيساو", code: "GW", en: "Guinea-Bissau" },
    GY: { ar: "غيانا", code: "GY", en: "Guyana" },
    HK: { ar: "هونغ كونغ الصينية", code: "HK", en: "Hong Kong" },
    HM: {
      ar: "جزيرة هيرد وجزر ماكدونالد",
      code: "HM",
      en: "Heard and McDonald Islands",
    },
    HN: { ar: "هندوراس", code: "HN", en: "Honduras" },
    HR: { ar: "كرواتيا", code: "HR", en: "Croatia" },
    HT: { ar: "هايتي", code: "HT", en: "Haiti" },
    HU: { ar: "هنغاريا", code: "HU", en: "Hungary" },
    ID: { ar: "إندونيسيا", code: "ID", en: "Indonesia" },
    IE: { ar: "أيرلندا", code: "IE", en: "Ireland" },
    IL: { ar: "إسرائيل", code: "IL", en: "Israel" },
    IN: { ar: "الهند", code: "IN", en: "India" },
    IO: {
      ar: "الإقليم البريطاني في المحيط الهندي",
      code: "IO",
      en: "British Indian Ocean Territory",
    },
    IQ: { ar: "العراق", code: "IQ", en: "Iraq" },
    IR: { ar: "إيران", code: "IR", en: "Iran" },
    IS: { ar: "أيسلندا", code: "IS", en: "Iceland" },
    IT: { ar: "إيطاليا", code: "IT", en: "Italy" },
    JM: { ar: "جامايكا", code: "JM", en: "Jamaica" },
    JO: { ar: "الأردن", code: "JO", en: "Jordan" },
    JP: { ar: "اليابان", code: "JP", en: "Japan" },
    KE: { ar: "كينيا", code: "KE", en: "Kenya" },
    KG: { ar: "قرغيزستان", code: "KG", en: "Kyrgyz Republic" },
    KH: { ar: "كمبوديا", code: "KH", en: "Cambodia" },
    KI: { ar: "كيريباتي", code: "KI", en: "Kiribati" },
    KM: { ar: "جزر القمر", code: "KM", en: "Comoros" },
    KN: { ar: "سانت كيتس ونيفيس", code: "KN", en: "St. Kitts and Nevis" },
    KP: { ar: "كوريا الشمالية", code: "KP", en: "North Korea" },
    KR: { ar: "كوريا الجنوبية", code: "KR", en: "South Korea" },
    KW: { ar: "الكويت", code: "KW", en: "Kuwait" },
    KY: { ar: "جزر الكايمن", code: "KY", en: "Cayman Islands" },
    KZ: { ar: "كازاخستان", code: "KZ", en: "Kazakhstan" },
    LA: { ar: "لاوس", code: "LA", en: "Lao People's Democratic Republic" },
    LB: { ar: "لبنان", code: "LB", en: "Lebanon" },
    LC: { ar: "سانت لوسيا", code: "LC", en: "St. Lucia" },
    LI: { ar: "ليختنشتاين", code: "LI", en: "Liechtenstein" },
    LK: { ar: "سريلانكا", code: "LK", en: "Sri Lanka" },
    LR: { ar: "ليبيريا", code: "LR", en: "Liberia" },
    LS: { ar: "ليسوتو", code: "LS", en: "Lesotho" },
    LT: { ar: "ليتوانيا", code: "LT", en: "Lithuania" },
    LU: { ar: "لوكسمبورغ", code: "LU", en: "Luxembourg" },
    LV: { ar: "لاتفيا", code: "LV", en: "Latvia" },
    LY: { ar: "ليبيا", code: "LY", en: "Libyan Arab Jamahiriya" },
    MA: { ar: "المغرب", code: "MA", en: "Morocco" },
    MC: { ar: "موناكو", code: "MC", en: "Monaco" },
    MD: { ar: "مولدافيا", code: "MD", en: "Moldova" },
    ME: { ar: "الجبل الأسود", code: "ME", en: "Montenegro" },
    MG: { ar: "مدغشقر", code: "MG", en: "Madagascar" },
    MH: { ar: "جزر المارشال", code: "MH", en: "Marshall Islands" },
    MK: { ar: "مقدونيا", code: "MK", en: "Macedonia" },
    ML: { ar: "مالي", code: "ML", en: "Mali" },
    MM: { ar: "ميانمار -بورما", code: "MM", en: "Myanmar" },
    MN: { ar: "منغوليا", code: "MN", en: "Mongolia" },
    MO: { ar: "مكاو الصينية (منطقة إدارية خاصة)", code: "MO", en: "Macao" },
    MP: {
      ar: "جزر ماريانا الشمالية",
      code: "MP",
      en: "Northern Mariana Islands",
    },
    MQ: { ar: "مارتينيك", code: "MQ", en: "Martinique" },
    MR: { ar: "موريتانيا", code: "MR", en: "Mauritania" },
    MS: { ar: "مونتسرات", code: "MS", en: "Montserrat" },
    MT: { ar: "مالطا", code: "MT", en: "Malta" },
    MU: { ar: "موريشيوس", code: "MU", en: "Mauritius" },
    MV: { ar: "جزر المالديف", code: "MV", en: "Maldives" },
    MW: { ar: "ملاوي", code: "MW", en: "Malawi" },
    MX: { ar: "المكسيك", code: "MX", en: "Mexico" },
    MY: { ar: "ماليزيا", code: "MY", en: "Malaysia" },
    MZ: { ar: "موزمبيق", code: "MZ", en: "Mozambique" },
    NA: { ar: "ناميبيا", code: "NA", en: "Namibia" },
    NC: { ar: "كاليدونيا الجديدة", code: "NC", en: "New Caledonia" },
    NE: { ar: "النيجر", code: "NE", en: "Niger" },
    NF: { ar: "جزيرة نورفوك", code: "NF", en: "Norfolk Island" },
    NG: { ar: "نيجيريا", code: "NG", en: "Nigeria" },
    NI: { ar: "نيكاراغوا", code: "NI", en: "Nicaragua" },
    NL: { ar: "هولندا", code: "NL", en: "Netherlands" },
    NO: { ar: "النرويج", code: "NO", en: "Norway" },
    NP: { ar: "نيبال", code: "NP", en: "Nepal" },
    NR: { ar: "ناورو", code: "NR", en: "Nauru" },
    NU: { ar: "نيوي", code: "NU", en: "Niue" },
    NZ: { ar: "نيوزيلاندا", code: "NZ", en: "New Zealand" },
    OM: { ar: "عُمان", code: "OM", en: "Oman" },
    PA: { ar: "بنما", code: "PA", en: "Panama" },
    PE: { ar: "بيرو", code: "PE", en: "Peru" },
    PF: { ar: "بولينيزيا الفرنسية", code: "PF", en: "French Polynesia" },
    PG: { ar: "بابوا غينيا الجديدة", code: "PG", en: "Papua New Guinea" },
    PH: { ar: "الفلبين", code: "PH", en: "Philippines" },
    PK: { ar: "باكستان", code: "PK", en: "Pakistan" },
    PL: { ar: "بولندا", code: "PL", en: "Poland" },
    PM: { ar: "سانت بيير وميكولون", code: "PM", en: "St. Pierre and Miquelon" },
    PN: { ar: "جزر بيتكيرن", code: "PN", en: "Pitcairn Island" },
    PR: { ar: "بورتوريكو", code: "PR", en: "Puerto Rico" },
    PS: { ar: "الأراضي الفلسطينية", code: "PS", en: "Palestinian Territory" },
    PT: { ar: "البرتغال", code: "PT", en: "Portugal" },
    PW: { ar: "بالاو", code: "PW", en: "Palau" },
    PY: { ar: "باراغواي", code: "PY", en: "Paraguay" },
    QA: { ar: "قطر", code: "QA", en: "Qatar" },
    RE: { ar: "روينيون", code: "RE", en: "Reunion" },
    RO: { ar: "رومانيا", code: "RO", en: "Romania" },
    RS: { ar: "صربيا", code: "RS", en: "Serbia" },
    RU: { ar: "روسيا", code: "RU", en: "Russia" },
    RW: { ar: "رواندا", code: "RW", en: "Rwanda" },
    SA: { ar: "المملكة العربية السعودية", code: "SA", en: "Saudi Arabia" },
    SB: { ar: "جزر سليمان", code: "SB", en: "Solomon Islands" },
    SC: { ar: "سيشل", code: "SC", en: "Seychelles" },
    SD: { ar: "السودان", code: "SD", en: "Sudan" },
    SE: { ar: "السويد", code: "SE", en: "Sweden" },
    SG: { ar: "سنغافورة", code: "SG", en: "Singapore" },
    SH: { ar: "سانت هيلنا", code: "SH", en: "St. Helena" },
    SI: { ar: "سلوفينيا", code: "SI", en: "Slovenia" },
    SJ: {
      ar: "سفالبارد وجان مايان",
      code: "SJ",
      en: "Svalbard & Jan Mayen Islands",
    },
    SK: { ar: "سلوفاكيا", code: "SK", en: "Slovakia" },
    SL: { ar: "سيراليون", code: "SL", en: "Sierra Leone" },
    SM: { ar: "سان مارينو", code: "SM", en: "San Marino" },
    SN: { ar: "السنغال", code: "SN", en: "Senegal" },
    SO: { ar: "الصومال", code: "SO", en: "Somalia" },
    SR: { ar: "سورينام", code: "SR", en: "Suriname" },
    SS: { ar: "جنوب السودان", code: "SS", en: "South Sudan" },
    ST: { ar: "ساو تومي وبرينسيبي", code: "ST", en: "Sao Tome and Principe" },
    SU: { ar: "Soviet Union", code: "SU", en: "Soviet Union" },
    SV: { ar: "السلفادور", code: "SV", en: "El Salvador" },
    SY: { ar: "سوريا", code: "SY", en: "Syrian Arab Republic" },
    SZ: { ar: "سوازيلاند", code: "SZ", en: "Swaziland" },
    TC: { ar: "جزر الترك وجايكوس", code: "TC", en: "Turks and Caicos Islands" },
    TD: { ar: "تشاد", code: "TD", en: "Chad" },
    TF: {
      ar: "المقاطعات الجنوبية الفرنسية",
      code: "TF",
      en: "French Southern Territories",
    },
    TG: { ar: "توجو", code: "TG", en: "Togo" },
    TH: { ar: "تايلاند", code: "TH", en: "Thailand" },
    TJ: { ar: "طاجكستان", code: "TJ", en: "Tajikistan" },
    TK: { ar: "توكيلو", code: "TK", en: "Tokelau" },
    TL: { ar: "تيمور الشرقية", code: "TL", en: "Timor-Leste" },
    TM: { ar: "تركمانستان", code: "TM", en: "Turkmenistan" },
    TN: { ar: "تونس", code: "TN", en: "Tunisia" },
    TO: { ar: "تونغا", code: "TO", en: "Tonga" },
    TP: { ar: "East Timor", code: "TP", en: "East Timor" },
    TR: { ar: "تركيا", code: "TR", en: "Turkey" },
    TT: { ar: "ترينيداد وتوباغو", code: "TT", en: "Trinidad and Tobago" },
    TV: { ar: "توفالو", code: "TV", en: "Tuvalu" },
    TW: { ar: "تايوان", code: "TW", en: "Taiwan" },
    TZ: { ar: "تانزانيا", code: "TZ", en: "Tanzania" },
    UA: { ar: "أوكرانيا", code: "UA", en: "Ukraine" },
    UG: { ar: "أوغندا", code: "UG", en: "Uganda" },
    UM: {
      ar: "جزر الولايات المتحدة النائية",
      code: "UM",
      en: "United States Minor Outlying Islands",
    },
    US: { ar: "الولايات المتحدة", code: "US", en: "United States of America" },
    UY: { ar: "أورغواي", code: "UY", en: "Uruguay" },
    UZ: { ar: "أوزبكستان", code: "UZ", en: "Uzbekistan" },
    VA: { ar: "الفاتيكان", code: "VA", en: "Holy See" },
    VC: {
      ar: "سانت فنسنت وغرنادين",
      code: "VC",
      en: "St. Vincent and the Grenadines",
    },
    VE: { ar: "فنزويلا", code: "VE", en: "Venezuela" },
    VG: { ar: "جزر فرجين البريطانية", code: "VG", en: "British Virgin Islands" },
    VI: { ar: "جزر فرجين الأمريكية", code: "VI", en: "US Virgin Islands" },
    VN: { ar: "فيتنام", code: "VN", en: "Vietnam" },
    VU: { ar: "فانواتو", code: "VU", en: "Vanuatu" },
    WF: { ar: "جزر والس وفوتونا", code: "WF", en: "Wallis and Futuna Islands" },
    WS: { ar: "ساموا", code: "WS", en: "Samoa" },
    XC: { ar: "Czechoslovakia", code: "XC", en: "Czechoslovakia" },
    XG: { ar: "East Germany", code: "XG", en: "East Germany" },
    XI: { ar: "Northern Ireland", code: "XI", en: "Northern Ireland" },
    XK: { ar: "كوسوفو", code: "XK", en: "Kosovo" },
    YE: { ar: "اليمن", code: "YE", en: "Yemen" },
    YT: { ar: "مايوت", code: "YT", en: "Mayotte" },
    YU: { ar: "Yugoslavia", code: "YU", en: "Yugoslavia" },
    ZA: { ar: "جنوب أفريقيا", code: "ZA", en: "South Africa" },
    ZM: { ar: "زامبيا", code: "ZM", en: "Zambia" },
    ZR: { ar: "Zaire", code: "ZR", en: "Zaire" },
    ZW: { ar: "زيمبابوي", code: "ZW", en: "Zimbabwe" },
  };
  